apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "srgc.fullname" . }}
  labels: {{- include "srgc.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.clusterIssuer | quote }}
    nginx.ingress.kubernetes.io/proxy-body-size: 10m
    nginx.ingress.kubernetes.io/proxy-read-timeout: "120"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: {{ .Values.ingressClassName | quote }}
  rules:
    - host: {{ .Values.host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "srgc.fullname" . }}
                port:
                  number: 3000
  tls:
    - hosts:
        - {{ .Values.host | quote }}
      secretName: {{ .Values.tlsSecretName | quote }}
