apiVersion: v1
kind: Service
metadata:
  name: {{ include "srgc.fullname" . }}
  labels: {{- include "srgc.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
  selector: {{- include "srgc.selectorLabels" . | nindent 4 }}
